name: Build Angular + .NET Core app (+ .NET tests)

on:
  push:
  #  branches:
  #    - master 
  #    - dev
  #pull_request:
  #  branches: 
  #    - master
  #    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Angular build
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Change directory
      run: cd ./ClientApp
    - name: npm dependencies
      run: npm install         
    - name: Build Angular app
      run: npm run build -- --prod
   
   # .NET Core build + testing
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
